development:
  adapter: sqlite3
  database: database.db

test:
  adapter: sqlite3
  database: database.db

production:
  adapter: postgresql
  # database: mission
  # username: username
  # password: password
  host: localhost
  url: <%= ENV["DATABASE_URL"] %>

# default: &default
#   adapter: postgresql
#   pool: 5
#   encoding: UTF8
#   timeout: 5000
#   port: 5432
#
# development:
#   <<: *default
#   username: <%= ENV['PG_USER'] %>
#   password: <%= ENV['PG_PASS'] %>
#   database: db/my_db_development
#
# test:
#   <<: *default
#   database: db/my_db_test
#
# production:
#   url: <%= ENV["DATABASE_URL"] %>
